# Generated by Django 4.0.2 on 2022-02-27 07:22

from django.db import migrations, models
import django.db.models.deletion
import expense_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.FileField(blank=True, null=True, upload_to=expense_app.utils.category_icon_directory_path)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='expense_app.category')),
            ],
            options={
                'verbose_name_plural': 'sub-categories',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expense_app.subcategory'),
        ),
    ]
